LIVRO_COMBO=["Genesis",
             "Exodo",
             "Levitico",
             "Numeros",
             "Deuteronomio",
             "Josue",
             "Juizes",
             "Rute",
             "1 Samuel",
             "2 Samuel",
             "1 Reis",
             "2 Reis",
             "1 Cronicas",
             "2 Cronicas",
             "Esdras",
             "Neemias",
             "Ester",
             "Jo",
             "Salmos",
             "Proverbios",
             "Eclesiastes",
             "Canticos",
             "Isaias",
             "Jeremias",
             "Lamentacoes",
             "Ezequiel",
             "Daniel",
             "Oseias",
             "Joel",
             "Amos",
             "Obadias",
             "Jonas",
             "Miqueias",
             "Naum",
             "Habacuque",
             "Sofonias",
             "Ageu",
             "Zacarias",
             "Malaquias",
             "Mateus",
             "Marcos",
             "Lucas",
             "Joao",
             "Atos",
             "Romanos",
             "1 Corintios",
             "2 Corintios",
             "Galatas",
             "Efesios",
             "Filipenses",
             "Colossenses",
             "1 Tessalonicenses",
             "2 Tessalonicenses",
             "1 Timoteo",
             "2 Timoteo",
             "Tito",
             "Filemon",
             "Hebreus",
             "Tiago",
             "1 Pedro",
             "2 Pedro",
             "1 Joao",
             "2 Joao",
             "3 Joao",
             "Judas",
             "Apocalipse"]

LIVRO_DB=["Genesis",
          "Exodo",
          "Levitico",
          "Numeros",
          "Deuteronomio",
          "Josue",
          "Juizes",
          "Rute",
          "I_Samuel",
          "II_Samuel",
          "I_Reis",
          "II_Reis",
          "I_Cronicas",
          "II_Cronicas",
          "Esdras",
          "Neemias",
          "Ester",
          "Jo",
          "Salmos",
          "Proverbios",
          "Eclesiastes",
          "Canticos",
          "Isaias",
          "Jeremias",
          "Lamentacoes",
          "Ezequiel",
          "Daniel",
          "Oseias",
          "Joel",
          "Amos",
          "Obadias",
          "Jonas",
          "Miqueias",
          "Naum",
          "Habacuque",
          "Sofonias",
          "Ageu",
          "Zacarias",
          "Malaquias",
          "Mateus",
          "Marcos",
          "Lucas",
          "Joao",
          "Atos",
          "Romanos",
          "I_Corintios",
          "II_Corintios",
          "Galatas",
          "Efesios",
          "Filipenses",
          "Colossenses",
          "I_Tessalonicenses",
          "II_Tessalonicenses",
          "I_Timoteo",
          "II_Timoteo",
          "Tito",
          "Filemon",
          "Hebreus",
          "Tiago",
          "I_Pedro",
          "II_Pedro",
          "I_Joao",
          "II_Joao",
          "III_Joao",
          "Judas",
          "Apocalipse"]

LIVRO_PT=["Gênesis",
          "Êxodo",
          "Levítico",
          "Números",
          "Deuteronômio",
          "Josué",
          "Juízes",
          "Rute",
          "1 Samuel",
          "2 Samuel",
          "1 Reis",
          "2 Reis",
          "1 Crônicas",
          "2 Crônicas",
          "Esdras",
          "Neemias",
          "Ester",
          "Jó",
          "Salmos",
          "Provérbios",
          "Eclesiastes",
          "Cânticos",
          "Isaías",
          "Jeremias",
          "Lamentações",
          "Ezequiel",
          "Dâniel",
          "Oseias",
          "Joel",
          "Amós",
          "Obadias",
          "Jonas",
          "Miqueias",
          "Naum",
          "Habacuque",
          "Sofonias",
          "Ageu",
          "Zacarias",
          "Malaquias",
          "Mateus",
          "Marcos",
          "Lucas",
          "João",
          "Atos",
          "Romanos",
          "1 Coríntios",
          "2 Coríntios",
          "Gálatas",
          "Efésios",
          "Filipenses",
          "Colossenses",
          "1 Tessalonicenses",
          "2 Tessalonicenses",
          "1 Timóteo",
          "2 Timóteo",
          "Tito",
          "Filemon",
          "Hebreus",
          "Tiago",
          "1 Pedro",
          "2 Pedro",
          "1 João",
          "2 João",
          "3 João",
          "Judas",
          "Apocalipse"]